language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script:
  - npm install -g serverless
  - npm run deploy

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest unit --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage